# Generated by Django 4.1.6 on 2023-02-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        help_text="quantidade do produto no estoque",
                        verbose_name="quantidade do produto no estoque",
                    ),
                ),
                (
                    "produto",
                    models.OneToOneField(
                        help_text="produto no estoque",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produto.produto",
                        verbose_name="produto no estoque",
                    ),
                ),
            ],
            options={
                "db_table": "estoque",
            },
        ),
    ]
