# Generated by Django 4.1.6 on 2023-02-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0002_produto_status_alter_produto_categoria_and_more"),
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoque",
            name="produto",
            field=models.OneToOneField(
                help_text="produto",
                on_delete=django.db.models.deletion.CASCADE,
                to="produto.produto",
                verbose_name="produto",
            ),
        ),
        migrations.AlterField(
            model_name="estoque",
            name="quantidade",
            field=models.PositiveIntegerField(
                help_text="quantidade", verbose_name="quantidade"
            ),
        ),
    ]
