# Generated by Django 4.1.6 on 2023-02-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categoria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                help_text="nome da categoria", max_length=100, verbose_name="nome"
            ),
        ),
    ]
