# Generated by Django 4.1.6 on 2023-02-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categoria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="nome do produto",
                        max_length=100,
                        verbose_name="nome do produto",
                    ),
                ),
                (
                    "preco",
                    models.FloatField(
                        help_text="preço do produto", verbose_name="preço do produto"
                    ),
                ),
                ("imagem", models.ImageField(upload_to="produto_imagens/")),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="categoria do produto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categoria.categoria",
                        verbose_name="categoria do produto",
                    ),
                ),
            ],
            options={
                "db_table": "produto",
            },
        ),
    ]
